stages:
  - lint
  - build
  - deploy

before_script:
  - git config --global --add safe.directory /builds/theopenstore/openstore-app/plugins/PamAuthentication
  - git config --global --add safe.directory /builds/theopenstore/openstore-app
  - git submodule update --init --recursive

check:
  stage: lint
  image: bhdouglass/openstore-app-tools
  script:
    - ./tools/docker/docker-runner.sh check-all

.artifacts:
  artifacts:
    expire_in: 1 week
    paths:
    - build/*/app/*.click

.matrix_build:
  parallel:
    matrix:
      - ARCH: arm64
        IMAGE_BASE: clickable/ci-20.04
        CLICKABLE_ARGS: ""
      - ARCH: armhf
        IMAGE_BASE: clickable/ci-20.04
        CLICKABLE_ARGS: ""
      - ARCH: amd64
        IMAGE_BASE: clickable/ci-20.04
        CLICKABLE_ARGS: ""
      - ARCH: arm64
        IMAGE_BASE: clickable/ci-ut26.04-1.x
        CLICKABLE_ARGS: "-c clickable-qt6.yaml"
      - ARCH: armhf
        IMAGE_BASE: clickable/ci-ut26.04-1.x
        CLICKABLE_ARGS: "-c clickable-qt6.yaml"
      - ARCH: amd64
        IMAGE_BASE: clickable/ci-ut26.04-1.x
        CLICKABLE_ARGS: "-c clickable-qt6.yaml"

.matrix_publish:
  parallel:
    matrix:
      - ARCH: arm64
        IMAGE_BASE: clickable/ci-20.04
        CLICKABLE_ARGS: ""
      - ARCH: armhf
        IMAGE_BASE: clickable/ci-20.04
        CLICKABLE_ARGS: ""
      - ARCH: amd64
        IMAGE_BASE: clickable/ci-20.04
        CLICKABLE_ARGS: ""

build:
  extends: [.artifacts, .matrix_build]
  stage: build
  image: $IMAGE_BASE-$ARCH
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - clickable build $CLICKABLE_ARGS

publish:
  extends: [.artifacts, .matrix_publish]
  stage: deploy
  image: $IMAGE_BASE-$ARCH
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - clickable build $CLICKABLE_ARGS
    - clickable publish "$CI_COMMIT_MESSAGE"
